apiVersion: v1
kind: Pod
metadata:
  name: pod-guest-v2
  labels:
    app: guest-v2
spec:
  containers:
  - name: container
    image: academyitwill/guest:v2
---
apiVersion: v1
kind: Service
metadata:
  name: service-guest-v2
spec:
  selector:
    app: guest-v2
  ports:
  - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-guest-v2
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-guest-v2
            port:
              number: 80